config/routes.rb
Rails.application.routes.draw do
  root to: "greetings#index"
  resources :greetings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/greeting.rb
class Greeting < ApplicationRecord
  validates :name, presence: :true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greeting, only: [:show, :edit, :update, :destroy]

  # GET /greetings
  # GET /greetings.json
  def index
    @greetings = Greeting.all.order(created_at: :desc)
  end

  # GET /greetings/1
  # GET /greetings/1.json
  def show
  end

  # GET /greetings/new
  def new
    @greeting = Greeting.new
  end

  # GET /greetings/1/edit
  def edit
  end

  # POST /greetings
  # POST /greetings.json
  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        format.html { redirect_to @greeting, notice: 'Greeting was successfully created.' }
        format.json { render :show, status: :created, location: @greeting }
      else
        format.html { render :new }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greetings/1
  # PATCH/PUT /greetings/1.json
  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to root_path, notice: 'Message sent.' }
        format.json { render :show, status: :ok, location: @greeting }
      else
        format.html { render :edit }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1
  # DELETE /greetings/1.json
  def destroy
    @greeting.destroy
    respond_to do |format|
      format.html { redirect_to greetings_url, notice: 'Greeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_greeting
    @greeting = Greeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def greeting_params
    params.require(:greeting).permit(:name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
  def gravatarized_url(name)
    hash = Digest::MD5.hexdigest(name)
    "https://www.gravatar.com/avatar/#{hash}?d=wavatar"
  end
end

app/views/greetings/_form.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Send me a message!</h5>
    <%= form_with(model: greeting, local: true) do |form| %>
      <% if greeting.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(greeting.errors.count, "error") %>
            prohibited this greeting from being saved:
          </h2>
          <ul>
            <% greeting.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.text_field :name,
          placeholder: "Name",
          class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.text_area :message,
          placeholder: "Message",
          class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit "Send!",
          class: "btn btn-outline-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/greetings/edit.html.erb
<h1>Editing Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Show', @greeting %> |
<%= link_to 'Back', greetings_path %>

app/views/greetings/index.html.erb
<p id="notice"><%= notice %></p>
<%= render("form", greeting: Greeting.new) %>
<br/>
<% @greetings.each do |greeting| %>
  <div class="media">
    <img src="<%= gravatarized_url(greeting.name) %>"
      class="align-self-start mr-3">
    <div class="media-body">
      <h5 class="mt-0"><%= greeting.name %></h5>
      <%= simple_format(greeting.message) %>
    </div>
  </div>
  <br/>
<% end %>

app/views/greetings/new.html.erb
<h1>New Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Back', greetings_path %>

app/views/greetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @greeting.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @greeting.message %>
</p>

<%= link_to 'Edit', edit_greeting_path(@greeting) %> |
<%= link_to 'Back', greetings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guesto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <main role="main" class="container">
      <%= yield %>
    </main>
    <footer class="footer">  
      <div class="container">
        <span class="text-muted">
          Guesto by Yourname
        </span>
      </div>
    </footer>
  </body>
</html>